Artist.create(name: "Michael Jackson", age: rand(50), title: "King of Pop")
Artist.create(name: "Stevie Wonder", age: rand(50), title: "Little Stevie Wonder")
Artist.create(name: "Elvis Presley", age: rand(50), title: "the King")
Artist.create(name: "Whitney Houston", age: rand(50), title: "The Voice")
Artist.create(name: "Beyoncé", age: rand(50), title: "Destiny's Child")

Instrument.create(name: "Guitar", classification: "Strings")
Instrument.create(name: "Violin", classification: "Strings")
Instrument.create(name: "Flute", classification: "Woodwind")
Instrument.create(name: "Xylophone", classification: "Percussion")

Studio.create(instrument_id: rand(1..4), artist_id: rand(1..5))
Studio.create(instrument_id: rand(1..4), artist_id: rand(1..5))
Studio.create(instrument_id: rand(1..4), artist_id: rand(1..5))
Studio.create(instrument_id: rand(1..4), artist_id: rand(1..5))
Studio.create(instrument_id: rand(1..4), artist_id: rand(1..5))
Studio.create(instrument_id: rand(1..4), artist_id: rand(1..5))
Studio.create(instrument_id: rand(1..4), artist_id: rand(1..5))